name: greenstone
version: 0.0.1
description: A simple console application.
dependencies:
  shelf: '>=0.6.5+2 <0.7.0'
  test: '>=0.12.13+4 <0.13.0'
  shelf_route: '>=0.14.2 <0.15.0'
  build: '>=0.6.3 <0.7.0'
  uri: '>=0.11.0 <0.12.0'
  mustache: '>=0.2.5 <0.3.0'
  source_gen: '>=0.5.2 <0.6.0'
  path: '>=1.4.1 <2.0.0'
  build_runner: '>=0.1.1 <0.2.0'
