name: greenstone
version: 0.0.1
description: A simple console application.
dependencies:
  shelf: '>=0.6.5+2 <0.7.0'
  test: '>=0.12.13+4 <0.13.0'
  shelf_route: '>=0.14.2 <0.15.0'
  build: '>=0.3.0+3 <0.4.0'
  dogma_codegen:
    path: ../dogma-codegen
  dogma_source_analyzer:
    path: ../dogma-source-analyzer
